### ISSUE TITLE
Fails with List::Util <= 1.32

### ISSUE THREAD

**Issue by andk** [aereal/JSON-TypeInference#17]
As per subject. Sample fail report:

http://www.cpantesters.org/cpan/report/61204199

Error: "any" is not exported by the List::Util module

Compare https://metacpan.org/changes/distribution/Scalar-List-Utils#L78

1.33 -- Sun Oct 13 01:35 UTC 2013
- Added any, all, none, notall list reduction functions
  (inspired by List::MoreUtils)

HTH&&Thanks,
(Disclaimer: this was discovered by statistical analysis, I'm not speaking as a user)

**Comment by aereal** [comment]
Thanks your report, fixed by #18 and will be releeased soon.

**Comment by aereal** [comment]
Released https://metacpan.org/release/AEREAL/JSON-TypeInference-1.0.2
